"""Self-contained accessible GIF viewer for portable offline galleries."""


def viewer_markup():
    return '''<style>
.stage a,.stage{cursor:zoom-in}dialog.sticker-viewer{padding:18px;border:1px solid #b6cdc3;border-radius:8px;background:#fff;color:#183d37;width:min(560px,calc(100% - 24px));max-height:calc(100dvh - 24px);overflow:auto}
.sticker-viewer::backdrop{background:#132f28b8}.viewer-tools{display:flex;justify-content:space-between;gap:8px;align-items:center}.viewer-tools button{width:44px;height:44px;flex-shrink:0;border:1px solid #cad9d0;background:white;border-radius:6px;font-size:24px;cursor:pointer;color:inherit}.viewer-tools button:disabled{opacity:.35;cursor:default}.viewer-stage{display:flex;justify-content:center;margin:12px 0}.viewer-stage img{width:360px!important;height:auto!important;max-width:100%!important;aspect-ratio:1;object-fit:contain}.viewer-label{font-size:20px;margin:8px 0}.viewer-note{font-size:14px;line-height:1.5;overflow-wrap:anywhere}.viewer-download{color:#205f50}dialog button:focus-visible,figure a:focus-visible{outline:3px solid #338c77;outline-offset:3px}
</style><dialog class="sticker-viewer" id="sticker-viewer" aria-labelledby="viewer-label">
<div class="viewer-tools"><button id="viewer-back" title="返回表情列表" aria-label="返回表情列表">&#215;</button><span id="viewer-position"></span><button id="viewer-prev" title="上一张" aria-label="上一张">&#8249;</button><button id="viewer-next" title="下一张" aria-label="下一张">&#8250;</button></div>
<div class="viewer-stage"><img id="viewer-image" width="360" height="360" alt=""></div><h2 class="viewer-label" id="viewer-label"></h2><p class="viewer-note" id="viewer-note"></p><a id="viewer-download" class="viewer-download" download>GIF</a></dialog>
<script>(()=>{
const dialog=document.getElementById('sticker-viewer'),all=[...document.querySelectorAll('figure')],items=all.filter(f=>f.querySelector('img'));
let openedFromPage=false,returnFocus=null,savedScroll=0;
const visible=()=>items.filter(f=>!f.hidden),key=f=>f.querySelector('img').getAttribute('src'),label=f=>f.querySelector('strong')?.textContent||f.querySelector('figcaption')?.textContent||f.querySelector('img').alt;
function show(f){if(!f)return;const list=visible(),i=list.indexOf(f);document.getElementById('viewer-image').src=key(f);document.getElementById('viewer-image').alt=label(f);document.getElementById('viewer-label').textContent=label(f);document.getElementById('viewer-note').textContent=f.querySelector('small')?.textContent||'';document.getElementById('viewer-download').href=key(f);document.getElementById('viewer-position').textContent=(i+1)+' / '+list.length;document.getElementById('viewer-prev').disabled=i<=0;document.getElementById('viewer-next').disabled=i<0||i>=list.length-1;dialog.dataset.current=key(f);if(!dialog.open)dialog.showModal();}
function sync(){const src=new URLSearchParams(location.hash.slice(1)).get('sticker');if(src){show(items.find(f=>key(f)===src));}else if(dialog.open){dialog.close();window.scrollTo(0,savedScroll);returnFocus?.focus({preventScroll:true});openedFromPage=false;}}
function open(f,focus){savedScroll=window.scrollY;returnFocus=focus;openedFromPage=true;history.pushState(null,'','#'+new URLSearchParams({sticker:key(f)}));show(f);}
function close(){if(openedFromPage){history.back();}else{history.replaceState(null,'',location.pathname+location.search);sync();}}
for(const f of items){const img=f.querySelector('img');let anchor=img.closest('a');if(!anchor){anchor=document.createElement('a');anchor.href=key(f);img.replaceWith(anchor);anchor.append(img);}anchor.setAttribute('aria-label','查看 '+label(f));anchor.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();open(f,anchor);});}
function move(offset){const list=visible(),i=list.findIndex(f=>key(f)===dialog.dataset.current),f=list[i+offset];if(f){history.replaceState(null,'','#'+new URLSearchParams({sticker:key(f)}));show(f);}}
document.getElementById('viewer-back').onclick=close;document.getElementById('viewer-prev').onclick=()=>move(-1);document.getElementById('viewer-next').onclick=()=>move(1);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='ArrowRight'){e.preventDefault();move(1);}});window.addEventListener('popstate',sync);sync();
})()</script>'''
